language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install: cd client
script:
  - npm test
  - npm run build
after_success:
  - cd ..
  - npm install
  - npm start
